# Generated by Django 2.2.5 on 2019-09-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=18, unique=True)),
                ('skoro', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tovar',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tovar.Group'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='tags',
            field=models.ManyToManyField(to='tovar.Tag'),
        ),
        migrations.RunSQL(
            sql = 'alter table tovar_tovar alter column quantity set default 0;',
            reverse_sql = 'alter table tovar_tovar alter column quantity drop default;'
        )
    ]
