# Generated by Django 2.2.5 on 2019-09-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0002_auto_20190913_1521'),
    ]


    operations = [
        migrations.RunSQL(
            sql = 'alter table tovar_tovar add column picture bytea ;',
            reverse_sql= 'alter table tovar_tovar drop column picture ;',
        )
    ]
